### ISSUE TITLE
update people who want to use this lib

### ISSUE THREAD

**Issue by thebigredgeek** [thebigredgeek/apollo-resolvers#1]
Please write a note below, ideally with your slack username on apollo's slack, if you wanna know once this is released

**Comment by pulpfree** [comment]
Please let me know, my slack username is: @pulpfree

**Comment by wmertens** [comment]
Meep.

BTW, it would also be nice if we could somehow run resolver-middleware that gets executed for all resolutions. That would allow whitelisting some resolvers for unauthenticated access and make all the rest require it, no chance of missing a query.

**Comment by thebigredgeek** [comment]
@wmertens hmmm, can you explain further?  I honestly thought that by using parent resolvers middleware wouldn't be necessary, as multiple resolvers can use the same parent

**Comment by wmertens** [comment]
@thebigredgeek With parent resolvers, you have to assign parents to resolvers, but middleware is shared by all resolvers. Think of it as whitelisting vs blacklisting.

**Comment by thebigredgeek** [comment]
@pulpfree @wmertens this is live.  Docs still need some love.  I will finish them tomorrow

**Comment by thebigredgeek** [comment]
@wmertens feel free to extend `combineResolvers` and add the functionality you mentioned above.  I am intentionally providing a few tools to make graphql easier to work with in NodeJS rather than just creation of resolvers.

**Comment by wmertens** [comment]
🎉 Great! 👍 

You know what, I think one can assign a resolver to the query root - that would be shared by all queries, and it would basically be that middleware. Then it's just a matter of looking at the `info` argument to know what is being requested.

So an authentication checking resolver could check if there are no fields being requested except `authenticate()` and `user`. That way you can add queries without worry.

At least, I think so, I need to try it out, but it seems sound :)

**Comment by thebigredgeek** [comment]
Nice!  Yeah I think it might be worth adding some sugar to this lib for query root as well
