### ISSUE TITLE
RFC: Resolver composition

### ISSUE THREAD

**Issue by ch-andrewrhyne** [thebigredgeek/apollo-resolvers#11]
```js
export default combineResolvers([
  postResolvers,
  userResolvers,
], { baseResolver });
```

**Comment by n1ru4l** [comment]
@ch-andrewrhyne Hey could you provide sample code for `postResolvers`, `userRespolvers` and `baseResolver`? i am struggling in understanding how those could be composed.

**Comment by thebigredgeek** [comment]
^ That was me BTW haha.  Sure, what I mean is that it composes `baseResolver` into both `postResolvers` and `userResolvers`.  It's not composing `postResolvers` and `userResolvers` together.  Rather, it is applying the `baseResolver` to both as the parent resolver
