### ISSUE TITLE
Refactor to typescript

### ISSUE THREAD

**Issue by ch-andrewrhyne** [thebigredgeek/apollo-resolvers#12]

**Comment by lakhansamani** [comment]
@thebigredgeek has anyone started working on this ?

**Comment by thebigredgeek** [comment]
Not that I know of!

**Comment by lakhansamani** [comment]
Okay, thanks

I am starting work in the following fork
https://github.com/lakhansamani/apollo-resolvers

**Comment by thebigredgeek** [comment]
Work is happening [here](https://github.com/thebigredgeek/apollo-resolvers/pull/15)

**Comment by lakhansamani** [comment]
Done in PR #15
