### ISSUE TITLE
Looking for additional core contributors

### ISSUE THREAD

**Issue by ch-andrewrhyne** [thebigredgeek/apollo-resolvers#13]
Post here if you want core contrib access.  Looking for 1 or 2 people to help

**Comment by thebergamo** [comment]
I can help :D

**Comment by lakhansamani** [comment]
I would love to contribute

**Comment by mringer** [comment]
I'm currently using apollo-resolvers and apollo-errors in a project, I'd be happy to help out as well.

**Comment by thebigredgeek** [comment]
@mringer @lakhansamani @thebergamo are you guys still interested?  I don't have a lot of time right now and things need to be fixed!

**Comment by mringer** [comment]
I'm flying back from Austrailia tomorrow but I should have some time to take a look next week when I'm back home.

**Comment by thebigredgeek** [comment]
I think we are good now!  Thanks
