### ISSUE TITLE
4th resolve parameter: info

### ISSUE THREAD

**Issue by jdesmarais1** [thebigredgeek/apollo-resolvers#19]
Can you please add the 4th parameter to createResolver.  The info object contains some useful information when attempting to create more advanced resolvers.

**Comment by jakelacey2012** [comment]
@thebigredgeek I would like to help @jdesmarais1 on this issue could you please advice on the API changes. More specifically what you think needs to happen with the `childErrFn`, do we just want to add a fifth parameter.

If that is the case, I think I know where the changes need to be made. Inside `resolver.ts` we pass the arguments to the `childResFn` & `childErrFn` functions but the info parameter is left out could that simply added you think?

**Comment by arist0tl3** [comment]
Wondering if there is any traction on this? `Info` is proving to be very helpful to me in writing re-usable resolvers.

Thanks @jdesmarais1 for putting together that PR -- using your fork right now successfully. =)

**Comment by thebigredgeek** [comment]
There is an open PR!  Stay tuned

**Comment by thebigredgeek** [comment]
Merged with https://github.com/thebigredgeek/apollo-resolvers/pull/28

**Comment by thebigredgeek** [comment]
Released with https://github.com/thebigredgeek/apollo-resolvers/releases/tag/1.3.0
