### ISSUE TITLE
[Examples, Question] for database connection errors using MongoDB + apollo-errors + apollo-resolvers

### ISSUE THREAD

**Issue by ahsath** [thebigredgeek/apollo-resolvers#26]
Hello there!

This is what I did in order to handle database connection errors using MongoDB and 2 awesome packages
`apollo-errors` and `apollo-resolvers`.

First of all I created a middleware that handles the connection to MongoDB where the `client` is a promise that resolves to the [Connected client](http://mongodb.github.io/node-mongodb-native/3.0/api/MongoClient.html) and the `db` is the database instance.

Note that I am calling the next middleware even though there is an error or not and the same time attaching the client and the db instance to request object in order to be available in the context object, here is where I'm not sure if is safe or bad doing it in this way because in my case I'm doing a signup form and well I need to open a connection to the database every time the user makes a request.

```
const dbConnection  = async (req, res, next) => {
    try {
        const client = await MongoClient.connect('mongodb://localhost:27017')
        const db = client.db('myproject')
        req.client = client
        req.db = db
        next()
    } catch (error) {
        req.err = error.message
        next()
    }
}

app.use('/graphql', dbConnection, bodyParser.json(), graphqlExpress(req => {
    return {
        schema,
        formatError,
        context: {
            client: req.client,
            db: req.db,
            err: req.err
        }
    }
}))
```

Then I create a base resolver for unknown thrown errors and another one that get all the users from the database, note that in the last resolver I am checking if there is an error, again I don't know if is good or bad doing it this way.

```
const baseResolver = createResolver(
    null,
    (_, args, context, error) => {
        if (isInstance(error)) return error
        return new UnknownError({
            data: {
                message: 'Oops! Something went wrong'
            }
        })
    })

const getAllUsers = baseResolver.createResolver(
    (_, args, {
        client,
        db,
        err
    }) => {
        if (err) throw new DatabaseConnectionError({
            data: {
                message: err
            }
        })
        return ...
    })

```

```
const resolvers = {
    Query: {
        getAllUsers
    },
```

I could do this directly in a resolver called `dbConnectionResolver` and throw erros from there and spam `getAllUsers` from the previous one like so: `const getAllUsers = dbConnectionResolver.createResolver(...)` the problem though is if there is no errors thrown in the `dbConnectionResolver` I don't get access to the `client` and the `db` instance in the next resolver.

Surely I'm doing something wrong because of my lack of knowledge if somebody have some thoughts on this I'll appreciate it. Thanks.

**Comment by thebigredgeek** [comment]
This seems... odd.  Are you sure that the `context` is being stripped as you describe?

**Comment by ahsath** [comment]
Stripped how? I just need to get access to the `client and db` in every request I can't find a good solution on where should I put the db connection

**Comment by ahsath** [comment]
Is there a way to set the context in a resolver and return it to the next in the chain? I mean if there is an error with the database connection throw the error and stop

**Comment by thebigredgeek** [comment]
Well, the way you are wording this implies that the context you are setting in the GraphQLExpress middleware is somehow not present in your resolvers which very much shouldn't be the case.

**Comment by ahsath** [comment]
Is not that is not present it Is, I'm saying that if there is a way to set the context in any of the resolver

**Comment by ShynRou** [comment]
There is no need to to have a connection middleware with mongoDB, since MongoDBClient does the connection pooling for you. 
Here it's noted in their documentation:

[https://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html#mongoclient-connection-pooling](https://mongodb.github.io/node-mongodb-native/driver-articles/mongoclient.html#mongoclient-connection-pooling)

**Comment by thebigredgeek** [comment]
@ahsath you can certainly mutate the context!  if the `parent` resolver doesn't return a value, the child resolver will still be called.  This means the parent can mutate the context before it is passed to the child.

**Comment by ahsath** [comment]
Oh, I'll try that
