### ISSUE TITLE
Static type testing in TS not working: error 2339

### ISSUE THREAD

**Issue by rasmussyberg** [thebigredgeek/apollo-resolvers#27]
Example: 
When calling function createResolver from baseResolver TS reports an error.
error TS2339: Property 'createResolver' does not exist on type '(root: any, args?: {}, context?: {}) => Promise<any>'.

Example code readme.md
export const isAuthenticatedResolver = baseResolver.**createResolver**(

**Comment by mringer** [comment]
@rasmussyberg This is a duplicate of #22
