### ISSUE TITLE
Resolvers don't pass info

### ISSUE THREAD

**Issue by frankdugan3** [thebigredgeek/apollo-resolvers#3]
As best as I can tell, this implementation of resolvers does not pass along the `info` argument from [Apollo's resolver signature](http://dev.apollodata.com/tools/graphql-tools/resolvers.html#Resolver-function-signature). This breaks my usage of `fieldASTs` to skip unnecessary DB joins in the resolvers.

This would be a breaking change, but would you consider changing your resolver signature to match Apollo's? My use case represents only one of the many useful things that can be done with `info`.

```
resolver(root, args, context, info, errors) {}
```

**Comment by thebigredgeek** [comment]
@frankdugan3 yup!  Submit a PR?

**Comment by thebigredgeek** [comment]
branch is up

**Comment by frankdugan3** [comment]
Sure, I'll to get to it in the next day or two.

**Comment by thebigredgeek** [comment]
Schweet!
