### ISSUE TITLE
Minor typescript issues

### ISSUE THREAD

**Issue by doomsower** [thebigredgeek/apollo-resolvers#35]
All of them can be worked around with `any` and `!`, but it would be nice to see them fixed here.

First one:

```ts
export interface CreateResolverFunction {
  <R, E>(resFn: ResultFunction<R>, errFn?: ErrorFunction<E>): Resolver<R>
}

export const createResolver: CreateResolverFunction 
```

Probably `resFn` should be optional or nullable, because in your examples you use it like this: 
```js

export const baseResolver = createResolver(
   //incoming requests will pass through this resolver like a no-op
  null,

  /*
    Only mask outgoing errors that aren't already apollo-errors,
    such as ORM errors etc
  */
  (root, args, context, error) => isInstance(error) ? error : new UnknownError()
);
```

Or maybe there should be two types, one for module-level `createResolver` and one for `Resolver`'s `createResolver`

Second is that you define Resolver as
```ts
export interface Resolver<ResulType> {
  (root, args: {}, context: {}, info: {}): Promise<ResulType>
  createResolver?: CreateResolverFunction
  compose?: ComposeResolversFunction
}
```

As far as I get it, the only way to create resolver is via `createResolver` and it will always add `createResolver` and `compose`, so they shouldn't be optional in interface.

**Comment by doomsower** [comment]
Also I think it's good idea to export type definitions from this module too

**Comment by thebigredgeek** [comment]
PRs are welcome!

**Comment by doomsower** [comment]
Could you please publish this?

**Comment by thebigredgeek** [comment]
Live in 1.4.1
