### ISSUE TITLE
Nullable returns

### ISSUE THREAD

**Issue by imranolas** [thebigredgeek/apollo-resolvers#39]
Is it expected that returning null from a resolver should allow the request to continue to the child resolver?

Since null is a valid return type for nullable fields, it may be desired that a resolver returns an early null like so.

eg.
```js
const isAuthenticatedResolver = baseResolver.createResolver(
  (root, args, { isAuthenticated }) => {
    if (!isAuthenticated) return null;
  }
);
```

**Comment by mringer** [comment]
Do you have a test that frames the problem as you see it?

**Comment by thebigredgeek** [comment]
Yep this is correct behavior.  The use case I was optimizing for with parent resolvers was error throwing, not actual interception of calls with real data returns.  Happy to chat about a solution, though.

**Comment by imranolas** [comment]
Ok, it was a little ambiguous to me that this behaviour is indeed correct since returning non null/undefined returns data from the resolver.

It would however be pretty cool if this could support data returns including null but I understand that it's not the focus of this project.

**Comment by groundmuffin** [comment]
I'd like to have valid null returns also without propagation to child resolver. Instead, 'undefined' can de treated as before.
