### ISSUE TITLE
userModel cannot be resolved 

### ISSUE THREAD

**Issue by jamsheer-thottathil** [thebigredgeek/apollo-resolvers#6]
Is there any sample implementation available ?I am not able resolve userModel

**Comment by thebigredgeek** [comment]
Hey @jamsheer-thottathil, I am happy to help but I am having trouble understanding what you are saying here?  `userModel` is just an example model in the docs... it doesn't come included in `apollo-resolvers`

**Comment by thebigredgeek** [comment]
I'm closing this for now.  If you clarify your question, @jamsheer-thottathil, I'd be happy to re-open it
