### ISSUE TITLE
Restify + GraphQL + Apollo + Firebase Auth Possible?

### ISSUE THREAD

**Issue by MichelDiz** [thebigredgeek/apollo-resolvers#7]
Hi, i'm right now studying those themes mentioned above. That's the question (above).

I'm creating a simple GraphQL API structure to learn about it. And I wish to integrate it with Firebase Auth. Couse I'm studying about the Auth from FB to use in a React Native client.

And I'm venturing into Restify xD

Many thanks,

Best Regards.

**Comment by thebigredgeek** [comment]
Hi @MichelDiz , I'd love to help but I am having a hard time understanding your question.  Could you clarify a bit for me as to what you'd like to know about the library?

**Comment by MichelDiz** [comment]
Hi!

I was trying to accomplish something into Restify.

Well, I'm doing right now a test with Express-firebase module - But I've been able to do it right without a module auth Middleware. Just using this code below
```
admin.auth().verifyIdToken(idToken)
  .then(function(decodedToken) {
    var uid = decodedToken.uid;
    // ...
    console.log("Sucesso", decodedToken);
  }).catch(function(error) {
    // Handle error   
   // console.log("decodedToken:", tokenGer);
    console.log("Error verify IdToken:", error);

  });
```
My goal is to validate an external user/client (React or React-Native) so that it has access to GraphQL. I'm doing this to secure my GraphQL Queries.

So I'm using 
`import { graphqlExpress, graphiqlExpress,  SubscriptionManager } from 'graphql-server-express';`


I'm able to validate the user Token with success and now I'm working on the routes.

**Comment by thebigredgeek** [comment]
Is you question related to `apollo-resolvers`?

**Comment by MichelDiz** [comment]
Oh yeah! I forgot to mention
I'm planning to deal with the erros like u do. So I've been studying over and found your YT video and your related repository.

From there I began to study about Apollo and Apollo-resolvers.

https://github.com/thebigredgeek/talk-apollo-day-04-12-2017

**Comment by MichelDiz** [comment]
But, forget it. i'm doing my way. Just traced my plan of study. Sure I'll use Apollo xD

Many thanks for your time man.

Best Regards

**Comment by pbrink231** [comment]
in the firebase client:
```
const client = new ApolloClient({	
	uri: clientUrl,
  request: async operation => {
    const fireToken = await Firebase.token();
    operation.setContext({
      headers: {
        authorization: fireToken ? `Bearer ${fireToken}` : 'token bad'
      }
    });
 	}
});
```
server:
```
app.use(
	'/graphql',
	express.json(),
	graphqlExpress((request) => ({
		schema: schema,
		context: { 
			request: request,
		}
	})),
);
```
in resolver:
```
    test: {
      type: GraphQLString,
      resolve: (parentValues, args, context) => {
        let idToken = (context.request.headers && context.request.headers.authorization) ? context.request.headers.authorization : null;
        var newToken = idToken.replace("Bearer ", "");
        admin.auth().verifyIdToken(newToken)
        .then(function(decodedToken) {
          var uid = decodedToken.uid;
          console.log('uid decoded', uid);
          // ...
        }).catch(function(error) {
          // Handle error
          console.log('uid failed', error);
        });
        return 'GraphQL query OK';
      }
    }

```
